## **Google colab and pythone basics**

In [100]:
print ("heloo")

heloo


In [101]:
nos = [1,2,3,4,5,6,7,8,9]
type(nos)

list

In [102]:
my_phone = {"apple":"13pro","samsung":"s20","oppo":"a9","nokia":"n110"}
type(my_phone)

dict

In [103]:
print("my phone is " , my_phone["apple"])

my phone is  13pro


In [104]:
a = 4
if a > 5 :
  print("a is grater")
else :
  print ("a is smaller")

a is smaller


In [105]:
for i in range(5):
  print(i)

0
1
2
3
4


In [106]:
rabge?

Object `rabge` not found.


In [107]:
def my_function():
  print("this is my function")

In [108]:
my_function()

this is my function


In [109]:
def findsum (a,b,c = 10):
  return a+b+c

In [110]:
findsum(25,30)

65

In [111]:
findsum(25,20,30)

75

### ** Numpy introduction**

In [112]:
import numpy as np

In [113]:
a = np.array([1,2,3,4,5,6])
print (a)

[1 2 3 4 5 6]


In [114]:
b = np.array([[4,5,6],[7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [115]:
b.shape

(2, 3)

In [116]:
b[1,2] # 0 , 1 - 1 row , 0,1,2,- 2 colom = 9

9

In [117]:
print(b[1,1])

8


In [118]:
b[0,:] # 1 colom and all row

array([4, 5, 6])

In [119]:
b[:,1] # all colom and 2 nd row

array([5, 8])

In [120]:
b[0,0:5]

array([4, 5, 6])

In [121]:
b.shape

(2, 3)

In [122]:
c = np.array([[1,2,3,4,5,6],[9,8,7,6,5,4]])
c.shape


(2, 6)

In [123]:
d = c.reshape((6,2))
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [9, 8],
       [7, 6],
       [5, 4]])

In [124]:
d.shape

(6, 2)

In [125]:
print(d)
dt = d.transpose()
print("Transpose is")
print(dt)


[[1 2]
 [3 4]
 [5 6]
 [9 8]
 [7 6]
 [5 4]]
Transpose is
[[1 3 5 9 7 5]
 [2 4 6 8 6 4]]


In [126]:
x = np.array([[12,34],[56,78]])
y = np.array([[98,76,54],[12,34,56]])
print(x.shape, y.shape)

(2, 2) (2, 3)


In [127]:
z = np.dot(x,y) # row of 1st metrix = colom of 2nd metrix in multipication
z

array([[1584, 2068, 2552],
       [6424, 6908, 7392]])

In [133]:
data = np.loadtxt(open("array.txt","rb"),delimiter=",") #loadtxt - txt load function , file open, delimiter colom separate
data

array([[ 1., 22.],
       [ 3., 44.],
       [ 5., 66.],
       [ 7., 88.]])

In [134]:
data[0,1]

22.0